import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Bookmark,Building2,Check,ChevronRight,Compass,ExternalLink,Layers3,MapPin,Search,SlidersHorizontal,X} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import NaverMap from './components/NaverMap';
import {fetchBuildings,supabase} from './lib/supabase';
import {filterBuildings,formatArea,safeSourceUrl,type Building} from './lib/domain';
const initialQuery=new URLSearchParams(location.search).get('q')||'';
export default function App(){
 const [buildings,setBuildings]=useState<Building[]>([]),[load,setLoad]=useState<'loading'|'ready'|'error'|'setup'>(supabase?'loading':'setup');
 const [query,setQuery]=useState(initialQuery),[region,setRegion]=useState(''),[status,setStatus]=useState(''),[view,setView]=useState<'all'|'saved'>('all');
 const [selected,setSelected]=useState<string|null>(null),[compare,setCompare]=useState<string[]>([]),[showCompare,setShowCompare]=useState(false);
 const [saved,setSaved]=useState<Set<string>>(new Set()),[session,setSession]=useState<Session|null>(null),[login,setLogin]=useState(false),[email,setEmail]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),search=useRef<HTMLInputElement>(null);
 const refresh=useCallback(()=>{if(!supabase)return;setLoad('loading');fetchBuildings().then(data=>{setBuildings(data);setLoad('ready');}).catch(()=>setLoad('error'));},[]);
 useEffect(refresh,[refresh]);
 useEffect(()=>{if(!supabase)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive)setSession(data.session);});const {data}=supabase.auth.onAuthStateChange((_event,value)=>setSession(value));return()=>{alive=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{let alive=true;setSaved(new Set());if(session && supabase)supabase.from('favorites').select('building_id').then(({data,error})=>{if(!alive)return;if(error)setNotice('관심 건물을 불러오지 못했습니다.');else setSaved(new Set(data?.map(r=>r.building_id)));});return()=>{alive=false;};},[session]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==='k'){event.preventDefault();search.current?.focus();}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[]);
 useEffect(()=>{const url=new URL(location.href);query?url.searchParams.set('q',query):url.searchParams.delete('q');history.replaceState(null,'',url);},[query]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timer);},[notice]);
 const results=useMemo(()=>filterBuildings(buildings,query,region,status,view==='saved'?saved:undefined),[buildings,query,region,status,view,saved]);
 const active=buildings.find(b=>b.id===selected),regions=[...new Set(buildings.map(b=>b.region))].sort();
 const select=useCallback((id:string)=>setSelected(id),[]);
 const openDialog=()=>{setShowCompare(true);dialog.current?.showModal();};
 async function toggleSave(id:string){
  if(!supabase || !session){setLogin(true);return;}if(busy)return;setBusy(true);
  const exists=saved.has(id);const {error}=exists?await supabase.from('favorites').delete().eq('building_id',id).eq('user_id',session.user.id):await supabase.from('favorites').insert({building_id:id,user_id:session.user.id});
  setBusy(false);if(error){setNotice('저장하지 못했습니다. 다시 시도해 주세요.');return;}
  setSaved(previous=>{const next=new Set(previous);exists?next.delete(id):next.add(id);return next;});
 }
 function toggleCompare(id:string){setCompare(previous=>previous.includes(id)?previous.filter(v=>v!==id):previous.length<3?[...previous,id]:previous);if(compare.length===3&&!compare.includes(id))setNotice('최대 3개 건물을 비교할 수 있습니다.');}
 async function signIn(event:React.FormEvent){event.preventDefault();if(!supabase)return;setBusy(true);const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+import.meta.env.BASE_URL}});setBusy(false);setNotice(error?'로그인 메일을 보내지 못했습니다. 잠시 후 다시 시도해 주세요.':'이메일로 로그인 링크를 보냈습니다.');if(!error)setLogin(false);}
 return <div className="app"><aside className="sidebar"><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-mark">w.</span><span>Workplace<span className="brand-city">Seoul</span></span></a><div className="nav-label">WORKSPACE</div><nav aria-label="주 메뉴"><button className={view==='all'?'current':''} onClick={()=>setView('all')}><Compass size={18}/>공간 탐색<ChevronRight size={14}/></button><button className={view==='saved'?'current':''} onClick={()=>setView('saved')}><Bookmark size={18}/>관심 건물<span className="nav-count">{saved.size||''}</span></button></nav><div className="sidebar-note"><span>공간을 보는 새로운 기준</span><p>연면적 1만 평 이상의 오피스.<br/>한 건물씩, 깊이 있게.</p></div><div className="account"><span className="avatar">{session?'M':'W'}</span><button onClick={()=>session?supabase?.auth.signOut().then(({error})=>{if(error)setNotice('로그아웃하지 못했습니다.');}):setLogin(true)}>{session?'로그아웃':'로그인'}<ArrowUpRight size={14}/></button></div></aside>
 <main><header><div className="breadcrumb">Workplace Seoul <ChevronRight size={13}/><strong>{view==='all'?'공간 탐색':'관심 건물'}</strong></div><span className="scope"><span/>전국 · 연면적 1만 평 이상</span></header><section className="toolbar" aria-label="검색 및 필터"><div className="search"><Search size={18}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="건물명 또는 주소 검색" aria-label="건물 검색"/>{query?<button aria-label="검색 초기화" onClick={()=>setQuery('')}><X size={14}/></button>:<kbd>⌘ K</kbd>}</div><div className="filters"><label><MapPin size={14}/><select aria-label="권역" value={region} onChange={e=>setRegion(e.target.value)}><option value="">전국</option>{regions.map(r=><option key={r}>{r}</option>)}</select></label><label><Layers3 size={14}/><select aria-label="건물 상태" value={status} onChange={e=>setStatus(e.target.value)}><option value="">전체 상태</option><option value="operating">운영 중</option><option value="development">개발 중</option></select></label><span className="fixed-filter"><SlidersHorizontal size={14}/>1만 평 이상</span></div></section>
 <div className="workspace"><section className="results" aria-label="건물 목록"><div className="results-heading"><div><h1>{view==='all'?'오피스 둘러보기':'관심 건물'}</h1><p>{load==='ready'?`${results.length.toLocaleString()}개의 공간`:'공간의 안팎을 연결합니다'}</p></div><Building2 size={21}/></div><div className="results-scroll">{load!=='ready'?<div className="empty"><Building2 size={30}/><h2>{load==='loading'?'공간 정보를 불러오고 있습니다':load==='error'?'정보를 불러오지 못했습니다':'첫 번째 공간을 준비하고 있습니다'}</h2><p>{load==='setup'?'검증된 건물 정보를 이곳에서 만나보세요.':load==='error'?'연결 상태를 확인하고 다시 시도해 주세요.':'잠시만 기다려 주세요.'}</p>{load==='error'&&<button onClick={refresh}>다시 시도</button>}</div>:results.length===0?<div className="empty"><Search size={26}/><h2>{view==='saved'?'저장한 건물이 없습니다':'조건에 맞는 건물이 없습니다'}</h2><p>{view==='saved'?'관심 있는 건물의 북마크를 눌러보세요.':'다른 검색어나 지역으로 살펴보세요.'}</p></div>:results.map(b=><article key={b.id} className={`building-card ${b.id===selected?'selected':''}`}><button className="card-main" onClick={()=>select(b.id)}><span className="building-art"><Building2 size={32}/></span><span className="card-info"><span className="eyebrow">{b.region} · {b.status==='operating'?'운영 중':'개발 중'}</span><strong>{b.name}</strong><span className="address">{b.address}</span><span className="area">{formatArea(b.gross_area_m2)}<span>연면적{b.area_basis==='planned'?' · 계획':''}</span></span></span></button><div className="card-actions"><button aria-label={`${b.name} 관심 건물 ${saved.has(b.id)?'해제':'저장'}`} aria-pressed={saved.has(b.id)} disabled={busy} onClick={()=>toggleSave(b.id)}><Bookmark size={15} fill={saved.has(b.id)?'currentColor':'none'}/></button><button aria-pressed={compare.includes(b.id)} onClick={()=>toggleCompare(b.id)}>{compare.includes(b.id)?<Check size={14}/>:<Layers3 size={14}/>}비교</button><span>확인 {b.verified_on}</span></div></article>)}</div><footer>기준이 명확한 공간, 근거가 있는 정보.</footer></section>
 <section className="map-region" aria-label="공간 지도"><NaverMap buildings={results} selected={selected} onSelect={select}/>{active&&<aside className="detail"><div className="detail-top"><span className="eyebrow">{active.region} · {active.status==='operating'?'운영 중':'개발 중'}</span><button aria-label="건물 상세 닫기" onClick={()=>setSelected(null)}><X size={17}/></button></div><h2>{active.name}</h2><p className="address">{active.address}</p><p className="overview">{active.overview||'공간 소개를 준비하고 있습니다.'}</p><dl><div><dt>연면적{active.area_basis==='planned'?' (계획)':''}</dt><dd>{formatArea(active.gross_area_m2)}</dd></div><div><dt>층수</dt><dd>{active.floors_above!=null?`지상 ${active.floors_above}층`:'미확인'}{active.floors_below!=null?` · 지하 ${active.floors_below}층`:''}</dd></div><div><dt>준공연도</dt><dd>{active.completion_year||'미확인'}</dd></div><div><dt>주차</dt><dd>{active.parking_spaces!=null?`${active.parking_spaces}대`:'미확인'}</dd></div></dl><div className="source">출처 · {safeSourceUrl(active.source_url)?<a href={safeSourceUrl(active.source_url)} target="_blank" rel="noreferrer">{active.source_name}<ExternalLink size={11}/></a>:active.source_name}<br/>확인일 · {active.verified_on}</div></aside>}</section></div>
 {compare.length>0&&<div className="compare-bar"><Layers3 size={17}/><span>{compare.length}개 건물 선택</span><button onClick={()=>setCompare([])}>초기화</button><button className="primary" onClick={openDialog}>나란히 비교 <ChevronRight size={14}/></button></div>}</main>
 <dialog ref={dialog} onClose={()=>setShowCompare(false)} className="compare-dialog"><div className="dialog-heading"><h2>건물 비교</h2><button aria-label="비교 닫기" onClick={()=>dialog.current?.close()}><X/></button></div>{showCompare&&<div className="table-scroll"><table><thead><tr><th>기준</th>{compare.map(id=><th key={id}>{buildings.find(b=>b.id===id)?.name}</th>)}</tr></thead><tbody>{[['연면적',(b:Building)=>formatArea(b.gross_area_m2)],['면적 기준',(b:Building)=>b.area_basis==='actual'?'실제':'계획'],['주소',(b:Building)=>b.address],['준공연도',(b:Building)=>b.completion_year??'미확인'],['주차 대수',(b:Building)=>b.parking_spaces??'미확인'],['확인일',(b:Building)=>b.verified_on]].map(([label,fn])=><tr key={label as string}><th>{label as string}</th>{compare.map(id=><td key={id}>{(fn as (b:Building)=>string|number)(buildings.find(b=>b.id===id)!)}</td>)}</tr>)}</tbody></table></div>}</dialog>
 {login&&<LoginModal onClose={()=>setLogin(false)}><h2>관심 있는 공간을 모아보세요</h2><p>이메일로 받은 링크를 통해 로그인합니다.</p>{supabase?<form onSubmit={signIn}><label>이메일<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="primary" disabled={busy}>{busy?'전송 중…':'로그인 링크 받기'}</button></form>:<p className="muted">회원 서비스를 준비하고 있습니다.</p>}</LoginModal>}{notice&&<div className="toast" role="status">{notice}</div>}</div>;
}
function LoginModal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="login-dialog" onClose={onClose}><button className="close" aria-label="로그인 닫기" onClick={()=>ref.current?.close()}><X size={19}/></button>{children}</dialog>;}
