const $ = (selector, parent=document) => parent.querySelector(selector);
const $$ = (selector, parent=document) => [...parent.querySelectorAll(selector)];
const icon = (name) => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
// Illustrative records for UX review, not verified property information.
const buildings = [
 {id:'dtower',name:'광화문 D타워',address:'종로구 종로3길 17',region:'도심권',area:31764,year:2014,station:'광화문역',walk:3,floors:24,status:'operating',tags:['복합 편의시설','도심 접근성'],amenity:true,x:41,y:31,art:0,description:'도심의 업무공간과 다양한 일상 경험이 한 건물 안에서 이어지는 공간.'},
 {id:'grand',name:'그랑서울 타워 1',address:'종로구 종로 33',region:'도심권',area:26460,year:2014,station:'종각역',walk:2,floors:33,status:'operating',tags:['지하철 인접','상업시설'],amenity:true,x:63,y:40,art:1,description:'종로의 보행 동선과 지하 상업공간이 연결되는 업무공간.'},
 {id:'finance',name:'서울파이낸스센터',address:'중구 세종대로 136',region:'도심권',area:25324,year:2001,station:'광화문역',walk:5,floors:30,status:'operating',tags:['광화문 업무권역','편의시설'],amenity:true,x:37,y:57,art:2,description:'광화문과 시청 사이, 도심의 주요 업무 거점을 가까이 두는 공간.'},
 {id:'centro',name:'센트로폴리스 A동',address:'종로구 우정국로 26',region:'도심권',area:33200,year:2018,station:'종각역',walk:4,floors:26,status:'operating',tags:['넓은 기준층','업무·편의시설'],amenity:true,x:75,y:26,art:3,description:'넉넉한 업무공간과 다양한 편의시설을 함께 살펴볼 수 있는 도심 오피스.'},
 {id:'centerone',name:'센터원 동관',address:'중구 을지로5길 26',region:'도심권',area:25680,year:2011,station:'을지로입구역',walk:5,floors:32,status:'operating',tags:['청계천 인접','업무 편의'],amenity:true,x:71,y:63,art:4,description:'청계천의 보행 환경과 도심 업무 인프라를 함께 누리는 공간.'},
 {id:'sewoon',name:'세운 업무복합 개발',address:'중구 을지로 일대',region:'도심권',area:18500,year:2030,station:'을지로3가역',walk:6,floors:28,status:'development',tags:['개발 예정','업무복합'],amenity:false,x:87,y:78,art:5,description:'업무공간과 도심의 새로운 동선을 함께 계획하는 개발 자산의 예시.'},
 {id:'gangnam',name:'센터필드 이스트',address:'강남구 테헤란로 231',region:'강남권',area:31000,year:2021,station:'역삼역',walk:5,floors:36,status:'operating',tags:['업무·생활편의','테헤란로'],amenity:true,x:55,y:49,art:3,description:'테헤란로의 업무환경과 복합 편의시설을 함께 담은 공간.'},
 {id:'yeouido',name:'파크원 타워 1',address:'영등포구 여의대로 108',region:'여의도권',area:52000,year:2020,station:'여의도역',walk:7,floors:69,status:'operating',tags:['복합 편의시설','여의도'],amenity:true,x:45,y:43,art:1,description:'여의도 업무권역의 사무공간과 상업·휴식 공간을 연결하는 건물.'},
 {id:'busan',name:'부산국제금융센터',address:'부산 남구 문현금융로 40',region:'부산',area:36000,year:2014,station:'국제금융센터·부산은행역',walk:3,floors:63,status:'operating',tags:['금융 업무권역','지하철 인접'],amenity:true,x:54,y:47,art:2,description:'부산의 금융 업무 거점과 주변 공간을 함께 살펴보는 오피스.'}
];
function stored(key, fallback) {try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; }}
const validIds = value => Array.isArray(value) ? value.filter(id => buildings.some(b=>b.id===id)) : [];
const state={region:'도심권',status:'all',query:'',minArea:10000,subway:false,amenity:false,sort:'name',view:'explore',selected:'dtower',saved:new Set(validIds(stored('ws:saved',[]))),compare:new Set(),recent:validIds(stored('ws:recent',['dtower','centro'])),scale:1,panX:0,panY:0};
let toastTimer;
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2700)}
function saveState(){try{localStorage.setItem('ws:saved',JSON.stringify([...state.saved]));localStorage.setItem('ws:recent',JSON.stringify(state.recent))}catch{/* In private mode, the in-memory state remains usable. */}}
function artwork(kind=0){
 const palettes=[['#d4e0e0','#6d8588','#455e64','#aac1c5'],['#e0e5e0','#74847e','#4e635c','#b1c5bc'],['#d8e0e7','#7a8c9b','#506777','#bacbd7'],['#deded9','#8d9187','#606b60','#c2c9b9'],['#d8e3df','#80988e','#557b70','#b4cfc3'],['#e8e4db','#a5a395','#858b79','#d4d6c7']];
 const [sky,front,side,light]=palettes[kind%6];const twin=kind===1||kind===3;const stagger=kind===0;const stripes=Array.from({length:21},(_,i)=>`<path d="M${i*7+24} 12v193" stroke="${light}" stroke-width="1" opacity=".53"/>`).join('');
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 200" preserveAspectRatio="xMidYMid slice" role="img" aria-label="건물 분위기를 표현한 일러스트"><defs><linearGradient id="sky${kind}" x2="0" y2="1"><stop stop-color="${sky}"/><stop offset="1" stop-color="#f0f1e9"/></linearGradient><linearGradient id="glass${kind}" x2="1" y2=".8"><stop stop-color="${front}"/><stop offset="1" stop-color="${light}"/></linearGradient><clipPath id="tower${kind}"><path d="${stagger?'M23 57 71 38 71 20 106 12 106 184 23 190Z':twin?'M17 62 72 36 72 185 17 192Z M90 40 137 20 137 182 90 188Z':'M31 35 110 12 110 186 31 193Z'}"/></clipPath></defs><rect width="160" height="200" fill="url(#sky${kind})"/><path d="M0 169 21 150 35 154v46H0Z M120 129l40 11v60h-40" fill="#b3beb4" opacity=".55"/><g clip-path="url(#tower${kind})"><rect x="10" y="5" width="145" height="195" fill="url(#glass${kind})"/>${stripes}${Array.from({length:27},(_,i)=>`<path d="m5 ${i*7+12} 160-20" stroke="${side}" stroke-width="1.5" opacity=".58"/>`).join('')}<path d="m40 5 30 15 10 170-30 10Z" fill="white" opacity=".13"/></g><path d="${twin?'M72 36l12 9v138l-12 2Z M137 20l16 13v148l-16 1Z':'M110 12l28 27v149l-28-2Z'}" fill="${side}"/>${Array.from({length:25},(_,i)=>`<path d="m${twin?137:110} ${i*6+27} ${twin?16:28} 8" stroke="${front}" stroke-width="1"/>`).join('')}<path d="M0 198 160 179v21H0" fill="#c6cbbf"/><g fill="#738973" opacity=".9"><circle cx="7" cy="179" r="12"/><circle cx="154" cy="174" r="14"/><circle cx="142" cy="185" r="9"/></g><path d="M6 180v20m148-23v23" stroke="#88937b" stroke-width="2"/><rect x="36" y="181" width="21" height="17" fill="${side}" opacity=".5"/></svg>`;
}
function renderMapBase(){
 let lots='';let seed=67;const rand=()=>{seed=(seed*9301+49297)%233280;return seed/233280};
 for(let row=0;row<19;row++){for(let col=0;col<17;col++){const x=col*62+rand()*10,y=row*55+rand()*9;const w=26+rand()*26,h=21+rand()*21;if((x>285&&x<365)||(y>421&&y<476)||(x<270&&y>625&&y<825)||(x>760&&y<160))continue;lots+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${2+rand()*2}" fill="${['#e2e5de','#e5e8e0','#e7e9e3','#dee3d9'][Math.floor(rand()*4)]}" stroke="#d9ded2" stroke-width=".5"/>`}}
 const roads=['M-20 332 Q390 326 1030 334','M-10 682 Q430 670 1030 693','M340 -50 340 380 322 660 412 1060','M610 -30 611 322 659 475 652 1010','M855 -30 841 330 846 610 911 1040','M-30 907 Q250 843 465 832 T1020 881','M-30 163 612 173','M-20 532 324 528','M26 -20 41 450 97 840','M-50 450 Q260 431 393 446 T710 470 T1020 456'];
 $('#cityMap').innerHTML=`<rect width="1000" height="1000" fill="#f0f1ed"/>${lots}<path d="M44 632 248 624 288 778 172 844 46 786Z" fill="#dce6d7" stroke="#d3decb"/><path d="M775 53h171v133H797Z" fill="#e0e8d8"/><path d="M301 8h42v239h-42Z" fill="#e2e6d9"/><g fill="none" stroke-linejoin="round">${roads.map(d=>`<path d="${d}" stroke="#dfe3d9" stroke-width="28"/><path d="${d}" stroke="#fffefa" stroke-width="24"/>`).join('')}<path d="M20 446 Q270 431 405 449 T713 472 T1030 455" stroke="#d4dfd9" stroke-width="14"/><path d="M20 446 Q270 431 405 449 T713 472 T1030 455" stroke="#c4d8d4" stroke-width="8"/><path d="M-40 348H1030" stroke="#ddd7df" stroke-width="2" stroke-dasharray="5 4" opacity=".6"/><path d="M-40 701 650 694 1000 720" stroke="#cad9c4" stroke-width="2" stroke-dasharray="5 4" opacity=".8"/></g><g font-family="'IBM Plex Sans KR',sans-serif" font-size="12" fill="#a6ada0" text-anchor="middle"><text x="325" y="146" transform="rotate(-90 325 146)">광화문광장</text><text x="497" y="340">종로</text><text x="713" y="695">을지로</text><text x="460" y="470" fill="#8fa7a0" font-size="11">청계천</text><text x="837" y="128" fill="#9cae8d">탑골공원</text><text x="155" y="731" fill="#9cae8d">덕수궁</text><text x="284" y="515" transform="rotate(-90 284 515)">세종대로</text><text x="586" y="594" transform="rotate(-90 586 594)">남대문로</text><text x="780" y="213" fill="#a5ad9b">인사동</text><text x="518" y="774" fill="#a5ad9b">소공동</text><text x="797" y="849" fill="#a5ad9b">명동</text><text x="215" y="403" fill="#a5ad9b">신문로</text><text x="470" y="134" fill="#a5ad9b">수송동</text></g><g font-family="'IBM Plex Sans KR',sans-serif" font-size="11" fill="#8d9685">${[[329,340,'광화문','5'],[612,335,'종각','1'],[335,676,'시청','2'],[660,683,'을지로입구','2'],[850,690,'을지로3가','3']].map(([x,y,n,line])=>`<circle cx="${x}" cy="${y}" r="7" fill="#fffffc" stroke="#b8c2ac" stroke-width="2"/><text x="${x-3}" y="${y+3}" font-size="8">${line}</text><text x="${x+13}" y="${y+4}">${n}</text>`).join('')}</g><rect x="371" y="268" width="57" height="54" rx="3" fill="#ced8c5" stroke="#b4c3a8"/><rect x="562" y="367" width="73" height="49" rx="2" fill="#d3ddcb" stroke="#bdccb1"/><rect x="686" y="217" width="55" height="70" rx="2" fill="#d1dacb" stroke="#bdc9b4"/>`;
}
function matches(){let result=buildings.filter(b=>(state.region==='전체'||b.region===state.region)&&(state.status==='all'||b.status===state.status)&&b.area>=state.minArea&&(!state.subway||b.walk<=5)&&(!state.amenity||b.amenity)&&(!state.query||[b.name,b.address,b.station,b.region].join(' ').toLowerCase().includes(state.query.toLowerCase()))&&(state.view!=='saved'||state.saved.has(b.id)));return result.sort((a,b)=>state.sort==='area'?b.area-a.area:state.sort==='year'?b.year-a.year:a.name.localeCompare(b.name,'ko'))}
const statusLabel=b=>b.status==='operating'?'운영 중':'개발 예정';
const regionName=region=>region==='전체'?'전체 지역':region==='부산'?'부산':`서울 ${region}`;
function render(){const list=matches();if(state.selected&&!list.some(b=>b.id===state.selected))state.selected=null;
 $('#buildingList').innerHTML=list.length?list.map(b=>`<article class="building-card ${state.selected===b.id?'selected':''}" data-id="${b.id}" tabindex="0" role="button" aria-label="${b.name} 건물 미리보기"><div class="building-visual">${artwork(b.art)}<span class="visual-status ${b.status}">${statusLabel(b)}</span></div><div class="card-copy"><div class="card-heading"><h2>${b.name}</h2><button class="bookmark-button ${state.saved.has(b.id)?'saved':''}" data-save="${b.id}" aria-label="${b.name} ${state.saved.has(b.id)?'관심 해제':'관심 저장'}" aria-pressed="${state.saved.has(b.id)}">${icon('bookmark')}</button></div><p class="card-address">${b.address}</p><div class="card-facts"><span><b>${b.area.toLocaleString()}</b> 평</span><i class="fact-dot"></i><span>${b.year}${b.status==='development'?'년 예정':'년 준공'}</span></div><div class="card-transit">${icon('pin')}${b.station} · 도보 ${b.walk}분</div><div class="card-bottom"><div class="card-tags">${b.tags.map(t=>`<span class="card-tag">${t}</span>`).join('')}</div><button class="compare-toggle ${state.compare.has(b.id)?'on':''}" data-compare="${b.id}" aria-pressed="${state.compare.has(b.id)}">${icon(state.compare.has(b.id)?'check':'plus')}비교</button></div></div></article>`).join(''):`<div class="empty-state">${icon(state.view==='saved'?'bookmark':'search')}<h2>${state.view==='saved'?'이 조건에 저장된 건물이 없어요':'조건에 맞는 건물이 없어요'}</h2><p>${state.view==='saved'?'관심 있는 건물의 북마크를 눌러<br>나만의 목록을 만들어보세요.':'지역을 바꾸거나 검색 조건을 줄여보세요.<br>현재는 예시 건물로 살펴볼 수 있습니다.'}</p><button id="emptyReset">${state.view==='saved'?'전체 건물 둘러보기':'검색 조건 초기화'}</button></div>`;
 $('#resultCount').textContent=`${list.length}개 건물`;$('#resultRegion').textContent=regionName(state.region);$('#regionLabel').textContent=state.region==='전체'?'전체 지역':state.region==='부산'?'부산':`서울 · ${state.region}`;
 $('#pageTitle').textContent=state.view==='saved'?'관심 건물':'오피스 탐색';$('#breadcrumbTitle').textContent=state.view==='saved'?'관심 건물':'오피스 탐색';$('#pageDescription').textContent=state.view==='saved'?'관심 있는 공간을 모아, 다시 살펴보세요.':'건물 한 곳을, 더 깊이 이해하는 시작.';
 $('#savedCount').textContent=state.saved.size;$('#compareCount').textContent=state.compare.size;$('#areaLabel').textContent=`${state.minArea/10000}만 평 이상`;
 const filterCount=Number(state.minArea>10000)+Number(state.subway)+Number(state.amenity);$('#filterBadge').hidden=!filterCount;$('#filterBadge').textContent=filterCount;$('#resetFilters').hidden=!(filterCount||state.status!=='all'||state.query);
 $$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===state.view));$$('.region-nav').forEach(el=>el.classList.toggle('current',el.dataset.region===state.region));$$('[data-status]').forEach(el=>el.classList.toggle('selected',el.dataset.status===state.status));
 renderMarkers(list);renderRecent();renderCompareTray();if(state.selected)renderMapPreview(state.selected);else $('#mapPreview').hidden=true;
 // The custom CBD plan is intentionally only shown for the CBD sample region.
 $('#cityMap').style.opacity=state.region==='도심권'?'1':'.55';$$('#cityMap text').forEach(el=>el.style.display=state.region==='도심권'?'':'none');$('#mapLocationLabel').textContent=regionName(state.region);
}
function renderMarkers(list){$('#mapMarkers').innerHTML=list.map((b,index)=>{const x=state.region==='전체'?24+(index%3)*25:b.x,y=state.region==='전체'?28+Math.floor(index/3)*22:b.y;return `<button class="map-marker ${b.status} ${state.selected===b.id?'selected':''}" data-marker="${b.id}" style="left:${x}%;top:${y}%" aria-label="지도에서 ${b.name} 선택"><span class="marker-dot"></span>${b.name.replace('광화문 ','').replace(' 동관','').replace(' 타워 1','').replace(' A동','').replace(' 업무복합 개발',' 개발')}</button>`}).join('')}
function selectBuilding(id){state.selected=id;state.recent=[id,...state.recent.filter(v=>v!==id)].slice(0,4);saveState();render();if(document.body.classList.contains('list-layout'))openDetail(id)}
function renderMapPreview(id){const b=buildings.find(b=>b.id===id);$('#mapPreview').hidden=false;$('#mapPreview').innerHTML=`<div class="mini-visual">${artwork(b.art)}</div><div><strong>${b.name}</strong><p>${b.station} · 연면적 ${b.area.toLocaleString()}평</p><button class="preview-link" data-detail="${b.id}">건물 자세히 보기 ${icon('arrow')}</button></div><button class="icon-button" id="closeMapPreview" aria-label="미리보기 닫기">${icon('close')}</button>`}
function renderRecent(){$('#recentBuildings').innerHTML=state.recent.map(id=>{const b=buildings.find(b=>b.id===id);return b?`<button class="recent-button" data-detail="${id}">${icon('clock')}${b.name}</button>`:''}).join('')}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);saveState();render();notify(state.saved.has(id)?'관심 건물에 저장했습니다.':'관심 건물에서 해제했습니다.');if($('#detailDialog').open)updateDetailSave(id)}
function toggleCompare(id){if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size<3)state.compare.add(id);else return notify('한 번에 최대 3개 건물을 비교할 수 있습니다.');render();if($('#detailDialog').open)updateDetailSave(id)}
function renderCompareTray(){const count=state.compare.size;$('#compareTray').hidden=!count;$('#trayCount').textContent=`${count}개 건물 선택`;$('#trayNames').textContent=[...state.compare].map(id=>buildings.find(b=>b.id===id).name).join(' · ');$('#openCompare').disabled=count<2}
function openCompare(){if(state.compare.size<2){notify('목록에서 비교할 건물을 2개 이상 선택하세요.');return}const items=[...state.compare].map(id=>buildings.find(b=>b.id===id));$('#compareDialog').innerHTML=`<div class="dialog-heading"><div><h2>건물 비교</h2><p>같은 기준으로, 공간의 차이를 살펴보세요.</p></div><button class="icon-button" data-close aria-label="닫기">${icon('close')}</button></div><div class="compare-table-wrap"><table class="compare-table"><thead><tr><th>건물 개요</th>${items.map(b=>`<th><div class="compare-image">${artwork(b.art)}</div>${b.name}</th>`).join('')}</tr></thead><tbody>${[['상태',b=>statusLabel(b)],['연면적',b=>`${b.area.toLocaleString()} 평${b.status==='development'?' (계획)':''}`],['준공 시기',b=>`${b.year}년${b.status==='development'?' 예정':''}`],['지상 층수',b=>`${b.floors}층`],['가까운 역',b=>b.station],['접근성',b=>`도보 ${b.walk}분`],['공간의 특징',b=>b.tags.join(' · ')]].map(([label,fn])=>`<tr><th scope="row">${label}</th>${items.map(b=>`<td>${fn(b)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="detail-example-note">화면 구성 검토를 위한 예시 값입니다. 운영 사양과 개발 계획은 구분하여 표시합니다.</p>`;$('#compareDialog').showModal()}
function updateDetailSave(id){const save=$('[data-detail-save]', $('#detailDialog')),compare=$('[data-detail-compare]',$('#detailDialog'));if(save){save.innerHTML=icon('bookmark')+(state.saved.has(id)?'저장됨':'관심 저장');save.setAttribute('aria-pressed',state.saved.has(id))}if(compare){compare.innerHTML=icon(state.compare.has(id)?'check':'plus')+(state.compare.has(id)?'비교에 추가됨':'비교에 추가');compare.setAttribute('aria-pressed',state.compare.has(id))}}
function openDetail(id){const b=buildings.find(b=>b.id===id);state.recent=[id,...state.recent.filter(v=>v!==id)].slice(0,4);saveState();renderRecent();$('#detailDialog').innerHTML=`<div class="detail-top"><span>${regionName(b.region)} / 건물 상세</span><div><button class="icon-button" data-detail-share="${id}" aria-label="건물 주소 공유">${icon('share')}</button><button class="icon-button" data-close aria-label="닫기">${icon('close')}</button></div></div><div class="detail-content"><div class="detail-hero"><div class="detail-visual">${artwork(b.art)}</div><div><span class="detail-status">${statusLabel(b)}</span><h2>${b.name}</h2><p>${b.address}</p><p class="detail-description">${b.description}</p><div class="detail-actions"><button class="dark-button" data-detail-save="${id}"></button><button class="filter-button" data-detail-compare="${id}"></button></div></div></div><div class="detail-stats"><div><span>연면적${b.status==='development'?' · 계획':''}</span><strong>${b.area.toLocaleString()}<em>평</em></strong></div><div><span>준공${b.status==='development'?' 예정':''}</span><strong>${b.year}<em>년</em></strong></div><div><span>지상 규모</span><strong>${b.floors}<em>층</em></strong></div><div><span>${b.station}</span><strong>${b.walk}<em>분 도보</em></strong></div></div><nav class="detail-tabs" aria-label="건물 상세 항목"><button class="active" data-detail-tab="overview" data-building="${id}">건물 개요</button><button data-detail-tab="space" data-building="${id}">공간·편의</button><button data-detail-tab="location" data-building="${id}">입지·교통</button><button data-detail-tab="history" data-building="${id}">변화 이력</button></nav><div id="detailTabContent" class="detail-tab-content"></div><p class="detail-example-note">수치·설명은 예시이며 이미지는 건축 일러스트입니다. 실제 건물 정보는 검증 후 제공됩니다.</p></div>`;renderDetailTab(id,'overview');updateDetailSave(id);if(!$('#detailDialog').open)$('#detailDialog').showModal()}
function renderDetailTab(id,tab){const b=buildings.find(b=>b.id===id);$$('[data-detail-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.detailTab===tab));let rows=tab==='overview'?[['건물명',b.name],['용도','업무시설'],['주소',b.address],['상태',statusLabel(b)],['연면적',`${b.area.toLocaleString()}평`],['기준',b.status==='development'?'계획 면적 · 예시':'건물 전체 연면적 · 예시']]:tab==='space'?[['공간 특징',b.tags[0]],['편의시설',b.amenity?'식음·생활편의 공간':'계획 확인 필요'],['기준층 전용면적','확인 예정'],['주차 대수','확인 예정'],['시설 이용 조건','확인 예정'],['승강기·냉난방','확인 예정']]:tab==='location'?[['업무 권역',regionName(b.region)],['가까운 역',b.station],['접근 시간',`도보 ${b.walk}분 · 예시`],['주소',b.address],['거리 산정 기준','경로 확인 예정'],['주변 환경','상세 자료 확인 예정']]:[[b.status==='development'?'준공 계획':'준공',`${b.year}년 · 예시`],['명칭 변경','확인된 이력 없음'],['리모델링','확인된 이력 없음'],['소유·거래','확인된 이력 없음']];$('#detailTabContent').innerHTML=`<h3>${{overview:'건물의 기본 정보',space:'일하는 공간의 조건',location:'도시와 연결되는 위치',history:'건물이 지나온 시간'}[tab]}</h3><div class="detail-info-grid">${rows.map(([label,value])=>`<div class="detail-info-row"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>`}
function setRegion(region){state.region=region;state.selected=null;$('#regionMenu').hidden=true;$('#regionButton').setAttribute('aria-expanded','false');resetMap();render();closeMobileSidebar()}
function resetFilters(){state.status='all';state.query='';state.minArea=10000;state.subway=false;state.amenity=false;$('#searchInput').value='';render()}
function openFilters(){const form=$('#filterForm');form.elements.area.value=state.minArea;form.elements.subway.checked=state.subway;form.elements.amenity.checked=state.amenity;$('#filterDialog').showModal()}
function mapTransform(){$('#mapCanvas').style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.scale})`}
function resetMap(){state.scale=1;state.panX=0;state.panY=0;mapTransform();$('#searchMapArea').hidden=true}
function closeMobileSidebar(){document.body.classList.remove('mobile-sidebar');$('#mobileBackdrop').hidden=true}
function showSearch(){if(state.view==='saved'){state.view='explore';render()}$('#searchInput').focus();$('#searchInput').select();closeMobileSidebar()}
async function copyLink(id){const link=new URL(location.href);link.hash=id?`building=${id}`:'';link.searchParams.set('region',state.region);try{await navigator.clipboard.writeText(link.href);notify('주소를 복사했습니다.')}catch{notify('브라우저 주소창의 주소를 복사해 공유할 수 있습니다.')}}
document.addEventListener('click',event=>{
 const el=event.target.closest('button,a');if(!el)return;
 if(el.matches('[data-save]'))return toggleSave(el.dataset.save);
 if(el.matches('[data-compare]'))return toggleCompare(el.dataset.compare);
 if(el.matches('[data-marker]')){selectBuilding(el.dataset.marker);$(`.building-card[data-id="${el.dataset.marker}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'});return}
 if(el.matches('[data-detail]'))return openDetail(el.dataset.detail);
 if(el.matches('[data-detail-save]'))return toggleSave(el.dataset.detailSave);
 if(el.matches('[data-detail-compare]'))return toggleCompare(el.dataset.detailCompare);
 if(el.matches('[data-detail-share]'))return copyLink(el.dataset.detailShare);
 if(el.matches('[data-detail-tab]'))return renderDetailTab(el.dataset.building,el.dataset.detailTab);
 if(el.matches('[data-close]'))return el.closest('dialog').close();
 if(el.matches('[data-region]'))return setRegion(el.dataset.region);
 if(el.matches('[data-status]')){state.status=el.dataset.status;render();return}
 if(el.matches('[data-view]')){if(el.dataset.view==='compare')return openCompare();state.view=el.dataset.view;if(state.view==='saved'){state.region='전체';resetFilters()}else render();closeMobileSidebar();return}
 if(el.matches('[data-layout]')){if(matchMedia('(max-width:680px)').matches){document.body.classList.toggle('map-expanded',el.dataset.layout==='split');document.body.classList.remove('list-layout')}else document.body.classList.toggle('list-layout',el.dataset.layout==='list');$$('[data-layout]').forEach(b=>b.classList.toggle('selected',b===el));return}
 if(el.matches('.sidebar-toggle')){if(matchMedia('(max-width:900px)').matches){document.body.classList.toggle('mobile-sidebar');$('#mobileBackdrop').hidden=!document.body.classList.contains('mobile-sidebar')}else document.body.classList.toggle('sidebar-collapsed');return}
 if(el.matches('.brand')){event.preventDefault();state.view='explore';setRegion('도심권');resetFilters();return}
 if(el.id==='emptyReset'){state.view='explore';state.region='전체';resetFilters();return}
});
$('#buildingList').addEventListener('click',event=>{if(event.target.closest('button'))return;const card=event.target.closest('[data-id]');if(card){if(matchMedia('(max-width:680px)').matches)openDetail(card.dataset.id);else selectBuilding(card.dataset.id)}});
$('#buildingList').addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-id]')){event.preventDefault();openDetail(event.target.dataset.id)}});
$('#buildingList').addEventListener('pointerover',event=>{const card=event.target.closest('[data-id]');if(card)$(`[data-marker="${card.dataset.id}"]`)?.classList.add('highlight')});
$('#buildingList').addEventListener('pointerout',event=>{const card=event.target.closest('[data-id]');if(card)$(`[data-marker="${card.dataset.id}"]`)?.classList.remove('highlight')});
$('#searchInput').addEventListener('input',event=>{state.query=event.target.value.trim();render()});
$('#sortSelect').addEventListener('change',event=>{state.sort=event.target.value;render()});
$('#regionButton').onclick=()=>{const menu=$('#regionMenu');menu.hidden=!menu.hidden;$('#regionButton').setAttribute('aria-expanded',String(!menu.hidden))};
document.addEventListener('click',event=>{if(!event.target.closest('.dropdown-wrap')){$('#regionMenu').hidden=true;$('#regionButton').setAttribute('aria-expanded','false')}});
$('#areaButton').onclick=openFilters;$('#moreFilters').onclick=openFilters;$('#resetFilters').onclick=resetFilters;
$('#filterForm').onsubmit=event=>{event.preventDefault();const form=event.currentTarget;state.minArea=Number(form.elements.area.value);state.subway=form.elements.subway.checked;state.amenity=form.elements.amenity.checked;$('#filterDialog').close();render()};
$('#clearFilterForm').onclick=()=>$('#filterForm').reset();
$('#clearComparison').onclick=()=>{state.compare.clear();render()};$('#openCompare').onclick=openCompare;
$('#aboutButton').onclick=()=>$('#aboutDialog').showModal();$('#workspaceButton').onclick=()=>{state.view='explore';setRegion('전체');resetFilters()};
$('#shareButton').onclick=()=>copyLink();$('#mobileBackdrop').onclick=closeMobileSidebar;
$('#zoomIn').onclick=()=>{state.scale=Math.min(1.7,state.scale+.15);mapTransform()};$('#zoomOut').onclick=()=>{state.scale=Math.max(.8,state.scale-.15);mapTransform()};$('#resetMap').onclick=()=>{resetMap();render()};
$('#expandMap').onclick=()=>{document.body.classList.toggle('map-expanded');document.body.classList.remove('list-layout')};
$('#searchMapArea').onclick=()=>{const rect=$('#mapPanel').getBoundingClientRect();const visibleIds=$$('.map-marker').filter(el=>{const p=el.getBoundingClientRect();return p.left<rect.right&&p.right>rect.left&&p.top<rect.bottom&&p.bottom>rect.top}).map(el=>el.dataset.marker);$$('.building-card').forEach(card=>card.hidden=!visibleIds.includes(card.dataset.id));$('#resultCount').textContent=`${visibleIds.length}개 건물`;$('#searchMapArea').hidden=true;notify(`현재 지도에 보이는 ${visibleIds.length}개 건물입니다.`)};
$('#mapPreview').addEventListener('click',event=>{if(event.target.closest('#closeMapPreview')){state.selected=null;render()}});
let drag=null;
$('#mapCanvas').addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;drag={x:event.clientX,y:event.clientY,startX:state.panX,startY:state.panY};$('#mapCanvas').setPointerCapture(event.pointerId);$('#mapCanvas').classList.add('dragging')});
$('#mapCanvas').addEventListener('pointermove',event=>{if(!drag)return;state.panX=Math.max(-200,Math.min(200,drag.startX+event.clientX-drag.x));state.panY=Math.max(-200,Math.min(200,drag.startY+event.clientY-drag.y));mapTransform();if(Math.abs(event.clientX-drag.x)+Math.abs(event.clientY-drag.y)>8)$('#searchMapArea').hidden=false});
function endDrag(){drag=null;$('#mapCanvas').classList.remove('dragging')}
$('#mapCanvas').addEventListener('pointerup',endDrag);$('#mapCanvas').addEventListener('pointercancel',endDrag);
document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();showSearch()}if(event.key==='Escape'){$('#regionMenu').hidden=true;$('#regionButton').setAttribute('aria-expanded','false');closeMobileSidebar()}});
$$('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}));
const initialParams=new URLSearchParams(location.search);if(['전체','도심권','강남권','여의도권','부산'].includes(initialParams.get('region')))state.region=initialParams.get('region');
renderMapBase();render();
if(matchMedia('(max-width:680px)').matches){$$('[data-layout]').forEach(el=>el.classList.toggle('selected',el.dataset.layout==='list'))}
const deepLink=location.hash.match(/^#building=([a-z]+)$/)?.[1];if(buildings.some(b=>b.id===deepLink))openDetail(deepLink);
